### ISSUE TITLE
Output piping doesn't work while using bash.exe, conemu etc.

### ISSUE THREAD

**Issue by jtc42** [imachug/win-sudo#35]
This seems similar to https://github.com/imachug/win-sudo/issues/6 but I can't find a functioning solution. Basically when I use win-sudo from a console launcher via mingw64.exe it works fine, but if I launch bash.exe through something like conemu, the output never gets piped back to the main process.

I tried a few things and it seems to be an issue that when it's not working, it's because the process path (eg /proc/12860/fg/1) doesn't exist, according to sudobackend.

Am I missing an obvious solution here?

Thanks

**Comment by jtc42** [comment]
Also worth mentioning the solution here https://github.com/imachug/win-sudo/issues/11 didn't help. 'cat' is in the path, so it finds cat without issue, just never pipes the output back.

**Comment by purplesyringa** [comment]
Hm, what's your ConEmu version? I'm quite sure this didn't work till December, 18 ([here's the issue on ConEmu repo](https://github.com/Maximus5/ConEmu/issues/1783)). However, I just reinstalled ConEmu and win-sudo works, as well as the test I used to test terminal emulation (see issue). Could you try to update ConEmu and check whether the issue was fixed?

**Comment by jtc42** [comment]
Okay this may well be the issue. It seems to work fine on one of my machines, but not the other. I'll check asap but assume it's something with my configuration rather than a win-sudo bug. Thanks for the pointer, and sorry for the slight timewaster-issue.
