### ISSUE TITLE
Command doesn't execute

### ISSUE THREAD

**Issue by filips123** [imachug/win-sudo#36]
When I try to execute a command with `sudo`, it doesn't execute. It shows UAC prompt but the command is never executed.

**Comment by niels-bosman** [comment]
Same for me. Although I do not get UAC prompt.

**Comment by patrickaxe** [comment]
I tried me too. It stopped when I tried "echo use for elevation" as shown in the gif.

**Comment by chrisdjali-wrld3d** [comment]
I was having the same issue. I've not fixed it, but when I change the line with the PowerShell command to 
```bash
if ! powershell.exe "Start-Process \"$(cygpath -w /bin/)bash\" \"$backend\", \"$fifoid\" -Verb RunAs -WorkingDirectory \"\$PWD\" -Wait; (\$Error[0]).InvocationInfo.Line"; then
```
the Bash window that appears complains that `/dev/cons1: No such device or address` when running the `$SHELL -c "$command_to_run" >"$stdout" 2>"$stderr" <"$stdin" &` line of `sudobackend`.

Hopefully this is useful information rather than a new problem I've introduced with my meddling.

**Comment by chrisdjali-wrld3d** [comment]
I *think* what's going on here is that the author was expecting `-WindowStyle Hidden` to work like `-NoNewWindow` where the process is spawned in the current console session, so then when the `sudo` script gets the filenames for its input and output, if it was connected up to the Cygwin pseudo device for the current console (e.g. `/dev/cons1`) the same device would be available from the `sudobackend` script. However, the backend script gets a fresh console, and can only see `/dev/cons2` due to what Cygwin's Special Filenames docs describe as *a restriction in Windows*.

The solution would be to switch from `-WindowStyle Hidden` to `-NoNewWindow`, but that's not part of the same parameter set as `-Verb`, so can't be used at the same time, and `-Verb RunAs` is where all the magic happens.

As for why this works for some people and not others, I think there's a difference between the MinTTY console Git Bash uses by default and other Windows consoles. If the console is MinTTY (e.g. Git Bash has been started directly) `sudo` works just fine and the `stdin`, `stdout`, and `stderr` `sudobackend` uses are all `/dev/pty0` (potentially with a different number). If the console is the Windows Command Host or VS Code's terminal is used, though, it doesn't work and they're all `/dev/cons0` (potentially with a different number). Maybe some special handling can be added so when the outer `sudo` is connected to a `/dev/consX` it sets up a different file the `sudobackend` script can talk to and copies input and output to it itself.

**Comment by amyhouseman** [comment]
Hi all, 
Not sure if you can help and I am a beginner so.. 

I am trying to use FastQC, but it contains JAVA files. Therefore I am trying to install JAVA to bash. I got to a point watching this video: https://www.youtube.com/watch?v=WI8JzsjW4yM&t=212s, where I need to install JAVA - I managed to install it to my windows control panel but not bash. So when I try to do their 'sudo apt-get install jdk-15.0.1' (( i have already set the pathway on windows to this C:\Program Files\Java\jdk-15.0.1)), first of all sudo says it does not exist, so I am a little stuck. 

Also, when downloading this sudo-win i manage to do this stage git clone https://guthub.com/imachug/win-sudo.git
but after that sudo pip install gevent - still says sudo doesn't exist. 

I'm sure there has to be an easier way to install java and FastQC but I don't know how or who to ask, do any of you know? Thanks! Amy

**Comment by raymondmgeni** [comment]
install node js

**Comment by riedel** [comment]
Fixed in 5b2d65b4d38ee612598fa94980dacfa6e64b79c7 ?

**Comment by chrisdjali-wrld3d** [comment]
Seems to be, although the Windows install I was initially hitting this issue on no longer exists, so I'm not testing it under *exactly* the same conditions as when I originally hit the problem.

**Comment by purplesyringa** [comment]
Guess we won't really be able to check this in any other way, then. Feel free to open another issue if this still happens
